const data = [
    {
        id: 1,
        name: "Paracetamol",
        info: "Paracetamol is a common painkiller used to treat aches and pain. It can also be used to reduce a high temperature.",
        image: "https://www.netmeds.com/images/product-v1/600x600/837692/dolo_1000_tablet_10s_566310_0_0.jpg",
        price: "50",
    },
    {
        id: 2,
        name: "Ibuprofen",
        info: "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used for relieving pain, helping with fever, and reducing inflammation.",
        image: "https://www.netmeds.com/images/product-v1/600x600/379177/brufen_200mg_tablet_15s_0_1.jpg",
        price: "75",
    },
    {
        id: 3,
        name: "Amoxicillin",
        info: "Amoxicillin is an antibiotic used to treat a number of bacterial infections. It is a penicillin-type antibiotic.",
        image: "https://www.netmeds.com/images/product-v1/600x600/380216/verclav_625mg_tablet_10s_434024_0_0.jpg",
        price: "120",
    },
    {
        id: 4,
        name: "Cetirizine",
        info: "Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing.",
        image: "https://www.netmeds.com/images/product-v1/600x600/399531/cetzine_syrup_60ml_47636_0_1.jpg",
        price: "60",
    },
    {
        id: 5,
        name: "Metformin",
        info: "Metformin is a medication used to treat type 2 diabetes. It helps control blood sugar levels.",
        image: "https://www.netmeds.com/images/product-v1/600x600/53613/glycomet_sr_500mg_tablet_20s_0_1.jpg",
        price: "150",
    },
    {
        id: 6,
        name: "Aspirin",
        info: "Aspirin is used to reduce fever and relieve mild to moderate pain from conditions such as muscle aches, toothaches, common cold, and headaches.",
        image: "https://www.netmeds.com/images/product-v1/600x600/9799/ecosprin_av_75_20mg_capsule_10s_31495_0_1.jpg",
        price: "40",
    },
    {
        id: 7,
        name: "Lisinopril",
        info: "Lisinopril is used to treat high blood pressure and heart failure. It is also used to improve survival after a heart attack.",
        image: "https://www.netmeds.com/images/product-v1/600x600/370050/lipril_2_5mg_tablet_15s_0_1.jpg",
        price: "200",
    },
    {
        id: 8,
        name: "Atorvastatin",
        info: "Atorvastatin is used to improve cholesterol levels and decrease your risk for a heart attack and stroke.",
        image: "https://www.netmeds.com/images/product-v1/600x600/861357/atorva_10mg_tablet_15s_98809_0_1.jpg",
        price: "180",
    },
    {
        id: 9,
        name: "Omeprazole",
        info: "Omeprazole is used to treat certain stomach and esophagus problems (such as acid reflux, ulcers). It works by decreasing the amount of acid your stomach makes.",
        image: "https://www.netmeds.com/images/product-v1/600x600/333947/omez_insta_20mg_mint_flavour_powder_5_9gm_40937_0_3.jpg",
        price: "90",
    },
    {
        id: 10,
        name: "Simvastatin",
        info: "Simvastatin is used to lower cholesterol and triglycerides in the blood. It may reduce the risk of heart attack, stroke, and related health conditions.",
        image: "https://www.netmeds.com/images/product-v1/600x600/333606/simvotin_10mg_tablet_10s_40870_0_1.jpg",
        price: "160",
    },
    {
        id: 11,
        name: "Levothyroxine",
        info: "Levothyroxine is used to treat an underactive thyroid (hypothyroidism). It replaces or provides more thyroid hormone, which is normally produced by the thyroid gland.",
        image: "https://www.netmeds.com/images/product-v1/600x600/822526/euthyrox_75mcg_tablet_100s_0_0.jpg",
        price: "130",
    },
    {
        id: 12,
        name: "Amlodipine",
        info: "Amlodipine is used to treat high blood pressure and chest pain (angina). Lowering high blood pressure helps prevent strokes, heart attacks, and kidney problems.",
        image: "https://www.netmeds.com/images/product-v1/600x600/412509/stamlo_2_5mg_tablet_30s_0_1.jpg",
        price: "110",
    },
    {
        id: 13,
        name: "Metoprolol",
        info: "Metoprolol is used to treat high blood pressure, chest pain (angina), and heart failure. It is also used to improve survival after a heart attack.",
        image: "https://www.netmeds.com/images/product-v1/600x600/49026/metocard_xl_25mg_tablet_10s_35726_0_1.jpg",
        price: "140",
    },
    {
        id: 14,
        name: "Losartan",
        info: "Losartan is used to treat high blood pressure and to help protect the kidneys from damage due to diabetes.",
        image: "https://www.netmeds.com/images/product-v1/600x600/44621/losar_25mg_tablet_15s_0_0.jpg",
        price: "170",
    },
    {
        id: 15,
        name: "Gabapentin",
        info: "Gabapentin is used to help control seizures in people with epilepsy. It is also used to relieve nerve pain following shingles (a painful rash due to herpes zoster infection).",
        image: "https://www.netmeds.com/images/product-v1/600x600/43860/gabantin_100mg_capsule_10s_35097_0_3.jpg",
        price: "190",
    },
    {
        id: 16,
        name: "Hydrochlorothiazide",
        info: "Hydrochlorothiazide is used to treat high blood pressure and fluid retention (edema). It helps prevent strokes, heart attacks, and kidney problems.",
        image: "https://www.netmeds.com/images/product-v1/600x600/360969/telma_h_40mg_tablet_15_s_0.jpg",
        price: "80",
    },
    {
        id: 17,
        name: "Furosemide",
        info: "Furosemide is a diuretic (water pill) used to reduce extra fluid in the body (edema) caused by conditions such as heart failure, liver disease, and kidney disease.",
        image: "https://www.netmeds.com/images/product-v1/600x600/364331/furoped_pineapple_flavour_oral_solution_30ml_107799_0_1.jpg",
        price: "90",
    },
    {
        id: 18,
        name: "Clopidogrel",
        info: "Clopidogrel is used to prevent heart attacks and strokes in persons with heart disease (recent heart attack), recent stroke, or blood circulation disease (peripheral vascular disease).",
        image: "https://www.netmeds.com/images/product-v1/600x600/404318/clopilet_75mg_tablet_15s_48059_0_1.jpg",
        price: "210",
    },
    {
        id: 19,
        name: "Montelukast",
        info: "Montelukast is used to prevent wheezing and shortness of breath caused by asthma and decrease the number of asthma attacks.",
        image: "https://www.netmeds.com/images/product-v1/600x600/325193/montek_10mg_tablet_10s_0_0.jpg",
        price: "150",
    },
    {
        id: 20,
        name: "Prednisone",
        info: "Prednisone is used to treat conditions such as arthritis, blood disorders, breathing problems, severe allergies, skin diseases, cancer, eye problems, and immune system disorders.",
        image: "https://www.netmeds.com/images/product-v1/600x600/964718/paedisone_m_cream_15gm_0_1.jpg",
        price: "130",
    },
    {
        id: 21,
        name: "Warfarin",
        info: "Warfarin is used to treat blood clots (such as in deep vein thrombosis-DVT or pulmonary embolus-PE) and/or to prevent new clots from forming in your body.",
        image: "https://www.netmeds.com/images/product-v1/600x600/899921/warf_5mg_tablet_30s_0_0.jpg",
        price: "100",
    },
    {
        id: 22,
        name: "Tramadol",
        info: "Tramadol is used to help relieve moderate to moderately severe pain. It is similar to opioid (narcotic) analgesics.",
        image: "https://www.netmeds.com/images/product-v1/600x600/948242/biotram_injection_2ml_0_0.jpg",
        price: "120",
    },
    {
        id: 23,
        name: "Alprazolam",
        info: "Alprazolam is used to treat anxiety and panic disorders. It belongs to a class of medications called benzodiazepines which act on the brain and nerves (central nervous system) to produce a calming effect.",
        image: "https://www.netmeds.com/images/product-v1/600x600/989769/alpradream_tablet_10s_0_0.jpg",
        price: "140",
    },
    {
        id: 24,
        name: "Clonazepam",
        info: "Clonazepam is used to prevent and control seizures. This medication is known as an anticonvulsant or antiepileptic drug.",
        image: "https://www.netmeds.com/images/product-v1/600x600/995706/clotas_md_0_25_tablet_15s_408329_0_3.jpg",
        price: "160",
    },
    {
        id: 25,
        name: "Fluoxetine",
        info: "Fluoxetine is used to treat depression, panic attacks, obsessive compulsive disorder (OCD), a certain eating disorder (bulimia), and a severe form of premenstrual syndrome (premenstrual dysphoric disorder).",
        image: "https://www.netmeds.com/images/product-v1/600x600/43824/fludac_20mg_capsule_15s_35090_0_2.jpg",
        price: "180",
    },
    {
        id: 26,
        name: "Citalopram",
        info: "Citalopram is used to treat depression. It may improve your energy level and feelings of well-being.",
        image: "https://www.netmeds.com/images/product-v1/600x600/364331/furoped_pineapple_flavour_oral_solution_30ml_107799_0_1.jpg",
        price: "170",
    },
    {
        id: 27,
        name: "Hydrocodone",
        info: "Hydrocodone is used to relieve severe pain. It is a narcotic analgesic and works in the brain to change how your body feels and responds to pain.",
        image: "https://www.netmeds.com/images/product-v1/600x600/858138/inlife_iron_folic_acid_tablets_60s_77970_0_4.jpg",
        price: "250",
    },
    {
        id: 28,
        name: "Doxycycline",
        info: "Doxycycline is an antibiotic used to treat bacterial infections, including pneumonia and other respiratory tract infections.",
        image: "https://www.netmeds.com/images/product-v1/150x150/1049146/doxyzone_100mg_injection_2ml_661881_0_0.jpg",
        price: "100",
    },
    {
        id: 29,
        name: "Clindamycin",
        info: "Clindamycin is used to treat bacterial infections, including skin, lungs, internal organs, and female reproductive organs.",
        image: "https://www.netmeds.com/images/product-v1/600x600/1065727/clindamycin_phosphate_nanz_gel_20gm_549450_0_0.jpg",
        price: "90",
    },
    {
        id: 30,
        name: "Azithromycin",
        info: "Azithromycin is used to treat a variety of bacterial infections, including respiratory infections and ear infections.",
        image: "https://www.netmeds.com/images/product-v1/600x600/398217/azicip_500mg_tablet_3s_0_1.jpg",
        price: "150",
    },
    {
        id: 31,
        name: "Chloroquine",
        info: "Chloroquine is used to prevent and treat malaria. It is also used to treat liver disease caused by protozoa.",
        image: "https://www.netmeds.com/images/product-v1/600x600/908035/lariago_injection_5ml_0_0.jpg",
        price: "60",
    },
    {
        id: 32,
        name: "Ciprofloxacin",
        info: "Ciprofloxacin is used to treat bacterial infections and works by stopping the growth of bacteria.",
        image: "https://www.netmeds.com/images/product-v1/600x600/378628/ciplox_eye_ear_drops_10ml_45160_0_1.jpg",
        price: "80",
    },
    {
        id: 33,
        name: "Tamsulosin",
        info: "Tamsulosin is used to treat the symptoms of an enlarged prostate by relaxing muscles in the prostate and bladder.",
        image: "https://www.netmeds.com/images/product-v1/600x600/403329/urimax_eco_pack_0_4mg_capsule_30s_47955_0_3.jpg",
        price: "200",
    },
    {
        id: 34,
        name: "Levofloxacin",
        info: "Levofloxacin is used to treat bacterial infections and is an antibiotic that works by stopping the growth of bacteria.",
        image: "https://www.netmeds.com/images/product-v1/600x600/330430/levoflox_750mg_tablet_5s_40244_0_1.jpg",
        price: "120",
    },
    {
        id: 35,
        name: "Pantoprazole",
        info: "Pantoprazole is used to treat stomach and esophagus problems such as acid reflux and ulcers.",
        image: "https://www.netmeds.com/images/product-v1/600x600/404219/pantodac_40mg_tablet_15s_48021_0_1.jpg",
        price: "110",
    },
    {
        id: 36,
        name: "Esomeprazole",
        info: "Esomeprazole is used to treat certain stomach and esophagus problems such as acid reflux and works by reducing stomach acid.",
        image: "https://www.netmeds.com/images/product-v1/600x600/411526/sompraz_40mg_tablet_15s_53259_0_3.jpg",
        price: "140",
    },
    {
        id: 37,
        name: "Loratadine",
        info: "Loratadine is an antihistamine that reduces the effects of natural histamine in the body, relieving allergy symptoms.",
        image: "https://www.netmeds.com/images/product-v1/600x600/44541/alaspan_10mg_tablet_10s_399659_0_1.jpg",
        price: "50",
    },
    {
        id: 38,
        name: "Oxycodone",
        info: "Oxycodone is used to treat moderate to severe pain. It works in the brain to change how your body feels and responds to pain.",
        image: "https://www.netmeds.com/images/product-v1/600x600/44733/medrol_4mg_tablet_10s_0_1.jpg",
        price: "300",
    },
    {
        id: 39,
        name: "Methotrexate",
        info: "Methotrexate is used to treat certain types of cancer, severe psoriasis, and rheumatoid arthritis.",
        image: "https://www.netmeds.com/images/product-v1/600x600/53669/folitrax_15mg_injection_1ml_0.jpg",
        price: "180",
    },
    {
        id: 40,
        name: "Allopurinol",
        info: "Allopurinol is used to treat gout and kidney stones by reducing the amount of uric acid made by the body.",
        image: "https://www.netmeds.com/images/product-v1/600x600/1149691/allorix_300_tablet_10s_788427_0_0.jpg",
        price: "90",
    },
    {
        id: 41,
        name: "Colchicine",
        info: "Colchicine is used to prevent or treat gout attacks by decreasing swelling and lessening the build-up of uric acid crystals.",
        image: "https://www.netmeds.com/images/product-v1/600x600/1035728/colchigout_0_5_tablet_10s_409906_0_1.jpg",
        price: "85",
    },
    {
        id: 42,
        name: "Methylprednisolone",
        info: "Methylprednisolone is a corticosteroid used to reduce inflammation and is used to treat a variety of medical conditions.",
        image: "https://www.netmeds.com/images/product-v1/600x600/44733/medrol_4mg_tablet_10s_0_1.jpg",
        price: "170",
    },
    {
        id: 43,
        name: "Prednisolone",
        info: "Prednisolone is a corticosteroid used to treat allergic disorders, skin conditions, ulcerative colitis, arthritis, and other medical conditions.",
        image: "https://www.netmeds.com/images/product-v1/600x600/344606/omnacortil_drops_10ml_0_1.jpg",
        price: "140",
    },
    {
        id: 44,
        name: "Tacrolimus",
        info: "Tacrolimus is used to prevent organ rejection after a transplant and works by weakening the immune system to help the body accept the transplanted organ.",
        image: "https://www.netmeds.com/images/product-v1/600x600/46977/tacroz_forte_ointment_20gm_35535_0_1.jpg",
        price: "250",
    },
    {
        id: 45,
        name: "Mycophenolate",
        info: "Mycophenolate is used to prevent rejection of kidney, heart, or liver transplants and works by weakening the immune system.",
        image: "https://www.netmeds.com/images/product-v1/600x600/407852/cellcept_500mg_tablet_10s_50096_0_1.jpg",
        price: "300",
    },
    {
        id: 46,
        name: "Sildenafil",
        info: "Sildenafil is used to treat erectile dysfunction and works by increasing blood flow to the penis.",
        image: "https://www.netmeds.com/images/product-v1/600x600/46013/manforce_50mg_tablet_9s_35392_0_1.jpg",
        price: "180",
    },
    {
        id: 47,
        name: "Tadalafil",
        info: "Tadalafil is used to treat erectile dysfunction and benign prostatic hyperplasia (BPH).",
        image: "https://www.netmeds.com/images/product-v1/600x600/323040/modula_5mg_tablet_10s_39602_0_1.jpg",
        price: "200",
    },
    {
        id: 48,
        name: "Finasteride",
        info: "Finasteride is used to treat male pattern hair loss and symptoms of benign prostatic hyperplasia (BPH).",
        image: "https://www.netmeds.com/images/product-v1/600x600/1064507/finast_1mg_tablet_10s_494200_0_0.jpg",
        price: "160",
    },
    {
        id: 49,
        name: "Duloxetine",
        info: "Duloxetine is used to treat major depressive disorder, general anxiety disorder, and nerve pain.",
        image: "https://www.netmeds.com/images/product-v1/600x600/23572/duzela_20mg_capsule_10s_34173_0_3.jpg",
        price: "150",
    },
    {
        id: 50,
        name: "Venlafaxine",
        info: "Venlafaxine is used to treat depression, anxiety, panic attacks, and social anxiety disorder.",
        image: "https://www.netmeds.com/images/product-v1/150x150/325225/veniz_xr_150mg_capsule_10s_277180_0_2.jpg",
        price: "140",
    },
    {
        id: 51,
        name: "Paroxetine",
        info: "Paroxetine is an antidepressant used to treat depression, panic attacks, and anxiety disorders.",
        image: "https://www.netmeds.com/images/product-v1/600x600/54356/paxidep_cr_25mg_tablet_10s_36176_0_3.jpg",
        price: "130",
    },
    {
        id: 52,
        name: "Sertraline",
        info: "Sertraline is an antidepressant used to treat depression, panic attacks, and anxiety disorders.",
        image: "https://www.netmeds.com/images/product-v1/600x600/389075/daxid_50mg_tablet_15s_46452_0_2.jpg",
        price: "160",
    },
    {
        id: 53,
        name: "Citalopram",
        info: "Citalopram is used to treat depression by helping to restore the balance of serotonin in the brain.",
        image: "https://www.netmeds.com/images/product-v1/600x600/407852/cellcept_500mg_tablet_10s_50096_0_1.jpg",
        price: "140",
    },
    {
        id: 54,
        name: "Escitalopram",
        info: "Escitalopram is used to treat depression and anxiety disorders by restoring the balance of serotonin.",
        image: "https://www.netmeds.com/images/product-v1/600x600/991514/recita_10_tablet_15s_0_1.jpg",
        price: "180",
    },
    {
        id: 55,
        name: "Risperidone",
        info: "Risperidone is used to treat schizophrenia, bipolar disorder, and irritability associated with autism.",
        image: "https://www.netmeds.com/images/product-v1/600x600/351471/sizodon_md_0_5mg_tablet_10s_42787_0_1.jpg",
        price: "190",
    },
    {
        id: 56,
        name: "Olanzapine",
        info: "Olanzapine is used to treat schizophrenia and bipolar disorder by affecting the balance of neurotransmitters in the brain.",
        image: "https://www.netmeds.com/images/product-v1/600x600/369362/olimelt_10mg_tablet_10s_44260_0_1.jpg",
        price: "210",
    },
    {
        id: 57,
        name: "Quetiapine",
        info: "Quetiapine is used to treat schizophrenia, bipolar disorder, and major depressive disorder.",
        image: "https://www.netmeds.com/images/product-v1/600x600/325750/qutiwel_25mg_tablet_10s_39983_0_1.jpg",
        price: "220",
    },
    {
        id: 58,
        name: "Lithium",
        info: "Lithium is used to treat and prevent manic episodes in people with bipolar disorder.",
        image: "https://www.netmeds.com/images/product-v1/600x600/850714/sbl_lithium_carbonicum_3x_tablet_25_gm_422204_0_0.jpg",
        price: "100",
    },
    {
        id: 59,
        name: "Aripiprazole",
        info: "Aripiprazole is used to treat schizophrenia and bipolar disorder, as well as irritability associated with autism.",
        image: "https://www.netmeds.com/images/product-v1/600x600/42302/arpizol_20mg_tablet_10s_34908_0_1.jpg",
        price: "240",
    },
    {
        id: 60,
        name: "Lamotrigine",
        info: "Lamotrigine is used to treat epilepsy and bipolar disorder by stabilizing electrical activity in the brain.",
        image: "https://www.netmeds.com/images/product-v1/600x600/801169/lamitor_dt_100mg_tablet_15_s_0.jpg",
        price: "230",
    }
];

export default data;